flux.Shard.Config:
  master.slave.pair.list:
  "{
    \"masterSlavePairList\" :
    [
        {
          \"shardId\":1,
          \"masterIp\": \"127.0.0.1\",
          \"masterIp\": \"127.0.0.1\",
          \"startKey\": \"00\",
          \"endKey\":   \"3f\"
        },
        {
          \"shardId\":2,
          \"masterIp\": \"127.0.0.1\",
          \"masterIp\": \"127.0.0.1\",
          \"startKey\": \"40\",
          \"endKey\":   \"7f\"
        },
        {
          \"shardId\":3,
          \"masterIp\": \"127.0.0.1\",
          \"masterIp\": \"127.0.0.1\",
          \"startKey\": \"80\",
          \"endKey\":   \"bf\"
        },
        {
          \"shardId\":4,
          \"masterIp\": \"127.0.0.1\",
          \"masterIp\": \"127.0.0.1\",
          \"startKey\": \"c0\",
          \"endKey\":   \"ff\"
        },
    ]
  }"
flux.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/fluxShard_"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 10
  hibernate.c3p0.max_size: 100

fluxReadOnly.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/fluxShard_"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 3
  hibernate.c3p0.max_size: 10

flux_redriver.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux_redriver"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 10
  hibernate.c3p0.max_size: 100

Dashboard:
  service.port: 9999
  service.acceptors: 5
  service.selectors: 10
  service.workers: 30

Api:
  service.port: 9998
  service.acceptors: 4
  service.selectors: 4
  service.workers: 200

routers:
  default:
    instancesPerNode: 5

task:
  maxTaskRetryCount: 10

runtime:
  actorsystem:
    metrics: false
    name: FluxSystem
    configname: application.conf
    maxTaskActorCreateRetries : -1

redriver:
  batchdelete:
    batchsize: 50
    intervalms: 1000
  batchread:
    batchsize: 100
    intervalms: 20000
  noOfPersistenceWorkers: 10

deploymentType: directory
deploymentUnitsPath: "/tmp/workflows/"
