flux.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 10
  hibernate.c3p0.max_size: 100

flux.Database:
  driverClass: "com.mysql.jdbc.Driver"
  user: "root"
  password: ""
  properties:
    charSet: "UTF-8"
  url: "jdbc:mysql://localhost:3306/flux"
  maxWaitForConnection: 10s
  validationQuery: "select 1"
  minSize: 50
  maxSize: 200
  evictionInterval: 10s
  minIdleTime: 60s

fluxReadOnly.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 3
  hibernate.c3p0.max_size: 10

flux_redriver.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux_redriver"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 10
  hibernate.c3p0.max_size: 100

Dashboard:
  service.port: 9999
  service.acceptors: 5
  service.selectors: 10
  service.workers: 25

Api:
  service.port: 9998
  service.acceptors: 4
  service.selectors: 4
  service.workers: 200

routers:
  default:
    instancesPerNode: 5

task:
  maxTaskRetryCount: 10

runtime:
  actorsystem:
    metrics: false
    name: FluxSystem
    configname: application.conf
    maxTaskActorCreateRetries : 10

redriver:
  batchdelete:
    batchsize: 50
    intervalms: 1000
  batchread:
    batchsize: 100
    intervalms: 20000
  noOfPersistenceWorkers: 10

deploymentType: directory
deploymentUnitsPath: "/tmp/workflows/"
