flux.Shard.Pair.Config: "{
                            \"shardPairModelList\" :
                                                  [
                                                      {
                                                        \"shardId\": 1,
                                                        \"masterIp\": \"127.0.0.1\",
                                                        \"slaveIp\": \"127.0.0.1\",
                                                        \"startKey\": \"00\",
                                                        \"endKey\":   \"ff\"
                                                      }
                                                  ]
                          }"
flux.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 1
  hibernate.c3p0.max_size: 1
  hibernate.c3p0.numHelperThreads: 1


fluxReadOnly.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 1
  hibernate.c3p0.max_size: 1
  hibernate.c3p0.numHelperThreads: 1

flux_scheduler.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux_scheduler"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 2
  hibernate.c3p0.max_size: 3
  hibernate.c3p0.numHelperThreads: 2

Dashboard:
  service.port: 9999
  service.acceptors: 5
  service.selectors: 10
  service.workers: 30

Api:
  service.port: 9998
  service.acceptors: 4
  service.selectors: 4
  service.workers: 30

routers:
  default:
    instancesPerNode: 5

task:
  maxTaskRetryCount: 10

runtime:
  actorsystem:
    metrics: false
    name: FluxSystem
    configname: application.conf
    maxTaskActorCreateRetries : -1

redriver:
  batchDelete:
    batchSize: 50
    intervalms: 1000
  batchRead:
    batchSize: 100
    intervalms: 20000
  noOfPersistenceWorkers: 5

eventScheduler:
  batchRead:
    batchSize: 50
    intervalms: 1000

deploymentType: directory
deploymentUnitsPath: "/tmp/workflows/"
